// !!! This is a file automatically generated by hipify!!!
// Fused implementation of the four ordered wall contacts in
// TensorVectorizedSimulator._walls_torch.
#include <torch/extension.h>
#include <c10/hip/HIPGuard.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime_api.h>

void wall_contacts_launch(float*, float*, const float*, const float*, const float*,
                          const float*, const float*, const bool*, bool*, int, int,
                          float, float, hipStream_t);

void walls(torch::Tensor pose, torch::Tensor velocity,
           torch::Tensor length, torch::Tensor width, torch::Tensor mass,
           torch::Tensor yaw_inertia_multiplier, torch::Tensor wall_mu,
           torch::Tensor active, torch::Tensor wall_contact,
           double field_length, double field_width) {
  TORCH_CHECK(pose.is_cuda() && velocity.is_cuda() && active.is_cuda(),
              "wall contacts require accelerator tensors");
  TORCH_CHECK(pose.scalar_type() == at::kFloat && velocity.scalar_type() == at::kFloat &&
              length.scalar_type() == at::kFloat && width.scalar_type() == at::kFloat &&
              mass.scalar_type() == at::kFloat && yaw_inertia_multiplier.scalar_type() == at::kFloat &&
              wall_mu.scalar_type() == at::kFloat && active.scalar_type() == at::kBool &&
              wall_contact.scalar_type() == at::kBool, "wall prototype dtype mismatch");
  TORCH_CHECK(pose.dim() == 3 && (pose.size(1) == 2 || pose.size(1) == 6) && pose.size(2) == 3 &&
              velocity.sizes() == pose.sizes(), "pose and velocity must be [world,2|6,3]");
  const auto n = pose.size(0);
  const auto robots = pose.size(1);
  TORCH_CHECK(length.sizes() == torch::IntArrayRef({n, robots}) &&
              width.sizes() == length.sizes() && mass.sizes() == length.sizes() &&
              yaw_inertia_multiplier.sizes() == length.sizes() &&
              wall_mu.sizes() == torch::IntArrayRef({n}) &&
              active.sizes() == torch::IntArrayRef({n}) &&
              wall_contact.sizes() == torch::IntArrayRef({n, robots, 2}), "wall contact shape mismatch");
  for (const auto& t : {pose, velocity, length, width, mass, yaw_inertia_multiplier,
                        wall_mu, active, wall_contact}) {
    TORCH_CHECK(t.is_contiguous() && t.device() == pose.device(),
                "wall contact tensors must be contiguous on one device");
  }
  c10::cuda::CUDAGuard guard(pose.device());
  wall_contacts_launch(pose.data_ptr<float>(), velocity.data_ptr<float>(),
      length.data_ptr<float>(), width.data_ptr<float>(), mass.data_ptr<float>(),
      yaw_inertia_multiplier.data_ptr<float>(), wall_mu.data_ptr<float>(),
      active.data_ptr<bool>(), wall_contact.data_ptr<bool>(),
      static_cast<int>(n), static_cast<int>(robots),
      static_cast<float>(field_length), static_cast<float>(field_width),
      c10::cuda::getCurrentCUDAStream(pose.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("walls", &walls, "Fused sequential robot-wall contacts (HIP)");
}
