// !!! This is a file automatically generated by hipify!!!
#include <torch/extension.h>
#include <ATen/Functions.h>
#include <c10/hip/HIPGuard.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime_api.h>

void candidate_distance_launch(const float*, const float*, const bool*, float*,
    int64_t, int64_t, hipStream_t);

std::tuple<torch::Tensor, torch::Tensor, torch::Tensor> candidates(
    torch::Tensor points, torch::Tensor robot_xy, torch::Tensor free) {
  TORCH_CHECK(points.is_cuda() && points.scalar_type() == at::kFloat &&
      points.dim() == 3 && points.size(2) == 2 && points.is_contiguous(),
      "points must be contiguous HIP float [N,P,2]");
  const auto n = points.size(0), p = points.size(1);
  TORCH_CHECK(robot_xy.is_cuda() && robot_xy.scalar_type() == at::kFloat &&
      robot_xy.sizes() == torch::IntArrayRef({n, 2}) && robot_xy.is_contiguous() &&
      robot_xy.device() == points.device(), "robot_xy must be contiguous HIP float [N,2]");
  TORCH_CHECK(free.is_cuda() && free.scalar_type() == at::kBool &&
      free.sizes() == torch::IntArrayRef({n, p}) && free.is_contiguous() &&
      free.device() == points.device(), "free must be contiguous HIP bool [N,P]");
  TORCH_CHECK(p >= 4, "at least four candidate positions are required");
  c10::cuda::CUDAGuard guard(points.device());
  auto distances = torch::empty({n, p}, points.options());
  candidate_distance_launch(points.data_ptr<float>(), robot_xy.data_ptr<float>(),
      free.data_ptr<bool>(), distances.data_ptr<float>(), n, p,
      c10::cuda::getCurrentCUDAStream(points.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  // Delegate selection to ATen. Tie-index order is backend-specific and may
  // vary across calls, especially for equal finite distances or +inf entries.
  auto result = at::topk(distances, 4, -1, false, true);
  auto nearest = std::get<0>(result);
  auto indices = std::get<1>(result);
  auto valid = at::isfinite(nearest);
  return {indices, valid, nearest};
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("candidates", &candidates, "Fused fuel-candidate distance/mask plus exact ATen topk");
}
