// !!! This is a file automatically generated by hipify!!!
#include <torch/extension.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime.h>

void update_3v3_launch(
    const bool*, const float*, const float*, const float*, float*, float*,
    bool*, int64_t*, const bool*, const bool*, const bool*, const bool*,
    const float*, float*, float*, const bool*, const int64_t*, int64_t*,
    int64_t*, int64_t*, int64_t*, int64_t*, int64_t*, int64_t*, int64_t*,
    bool*, bool*, float*, const float*, const float*, const float*,
    int, int, float, float, int, hipStream_t);

void update_3v3(torch::Tensor active, torch::Tensor pose, torch::Tensor length,
    torch::Tensor width, torch::Tensor piece_pos, torch::Tensor piece_vel,
    torch::Tensor piece_active, torch::Tensor piece_owner,
    torch::Tensor score_intent, torch::Tensor controlled,
    torch::Tensor deterministic, torch::Tensor defense_role,
    torch::Tensor match_elapsed, torch::Tensor next_intake,
    torch::Tensor next_score, torch::Tensor hub_active,
    torch::Tensor last_actions, torch::Tensor acquisition_count,
    torch::Tensor score_count, torch::Tensor auto_scores,
    torch::Tensor denied_count, torch::Tensor acquired_event,
    torch::Tensor scored_event, torch::Tensor passed_event,
    torch::Tensor denied_event, torch::Tensor last_hub_zone,
    torch::Tensor track_mask, torch::Tensor track_age,
    torch::Tensor hub_centers, torch::Tensor ferry_targets,
    torch::Tensor pass_zone_positions, double dt, double score_interval,
    int64_t capacity) {
  auto stream = c10::cuda::getCurrentCUDAStream(active.get_device());
  update_3v3_launch(active.data_ptr<bool>(), pose.data_ptr<float>(),
      length.data_ptr<float>(), width.data_ptr<float>(), piece_pos.data_ptr<float>(),
      piece_vel.data_ptr<float>(), piece_active.data_ptr<bool>(),
      piece_owner.data_ptr<int64_t>(), score_intent.data_ptr<bool>(),
      controlled.data_ptr<bool>(), deterministic.data_ptr<bool>(),
      defense_role.data_ptr<bool>(), match_elapsed.data_ptr<float>(),
      next_intake.data_ptr<float>(), next_score.data_ptr<float>(),
      hub_active.data_ptr<bool>(), last_actions.data_ptr<int64_t>(),
      acquisition_count.data_ptr<int64_t>(), score_count.data_ptr<int64_t>(),
      auto_scores.data_ptr<int64_t>(), denied_count.data_ptr<int64_t>(),
      acquired_event.data_ptr<int64_t>(), scored_event.data_ptr<int64_t>(),
      passed_event.data_ptr<int64_t>(), denied_event.data_ptr<int64_t>(),
      last_hub_zone.data_ptr<bool>(), track_mask.data_ptr<bool>(),
      track_age.data_ptr<float>(), hub_centers.data_ptr<float>(),
      ferry_targets.data_ptr<float>(), pass_zone_positions.data_ptr<float>(),
      active.size(0), piece_active.size(1), static_cast<float>(dt),
      static_cast<float>(score_interval), static_cast<int>(capacity), stream);
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("update", &update_3v3, "Fused six-robot gamepiece update (HIP)");
}
