// !!! This is a file automatically generated by hipify!!!
#include <torch/extension.h>
#include <ATen/Functions.h>
#include <c10/hip/HIPGuard.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime_api.h>

void candidate_rank_launch(const float*, const float*, const bool*, int64_t*,
    bool*, float*, int64_t, int64_t, hipStream_t);
void candidate_cost_nearby_launch(const float*, const float*, const float*,
    const float*, const bool*, const bool*, float*, bool*, int64_t, int64_t,
    float, hipStream_t);

void candidate_top4_nearby_launch(const float*, const float*, const float*,
    const float*, const bool*, const bool*, int64_t*, float*, bool*, int64_t,
    int64_t, float, hipStream_t);

std::tuple<torch::Tensor, torch::Tensor, torch::Tensor> candidates(
    torch::Tensor points, torch::Tensor robot_xy, torch::Tensor free) {
  TORCH_CHECK(points.is_cuda() && points.scalar_type() == at::kFloat &&
      points.dim() == 3 && points.size(2) == 2 && points.is_contiguous(),
      "points must be contiguous HIP float [N,P,2]");
  const auto n = points.size(0), p = points.size(1);
  TORCH_CHECK(robot_xy.is_cuda() && robot_xy.scalar_type() == at::kFloat &&
      robot_xy.sizes() == torch::IntArrayRef({n, 2}) && robot_xy.is_contiguous() &&
      robot_xy.device() == points.device(), "robot_xy must be contiguous HIP float [N,2]");
  TORCH_CHECK(free.is_cuda() && free.scalar_type() == at::kBool &&
      free.sizes() == torch::IntArrayRef({n, p}) && free.is_contiguous() &&
      free.device() == points.device(), "free must be contiguous HIP bool [N,P]");
  TORCH_CHECK(p >= 4, "at least four candidate positions are required");
  c10::cuda::CUDAGuard guard(points.device());
  auto indices = torch::empty({n, 4}, points.options().dtype(at::kLong));
  auto valid = torch::empty({n, 4}, points.options().dtype(at::kBool));
  auto nearest = torch::empty({n, 4}, points.options());
  candidate_rank_launch(points.data_ptr<float>(), robot_xy.data_ptr<float>(),
      free.data_ptr<bool>(), indices.data_ptr<int64_t>(), valid.data_ptr<bool>(),
      nearest.data_ptr<float>(), n, p,
      c10::cuda::getCurrentCUDAStream(points.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return {indices, valid, nearest};
}

std::tuple<torch::Tensor, torch::Tensor> candidate_costs_with_nearby(
    torch::Tensor points, torch::Tensor intake_xy, torch::Tensor robot_xy,
    torch::Tensor age, torch::Tensor free, torch::Tensor midfield,
    double age_weight) {
  TORCH_CHECK(points.is_cuda() && points.scalar_type() == at::kFloat &&
      points.dim() == 3 && points.size(2) == 2 && points.is_contiguous(),
      "points must be contiguous HIP float [N,P,2]");
  const auto n = points.size(0), p = points.size(1);
  auto check_xy = [&](const torch::Tensor& xy, const char* name) {
    TORCH_CHECK(xy.is_cuda() && xy.scalar_type() == at::kFloat &&
        xy.sizes() == torch::IntArrayRef({n, 2}) && xy.is_contiguous() &&
        xy.device() == points.device(), name, " must be contiguous HIP float [N,2]");
  };
  check_xy(intake_xy, "intake_xy");
  check_xy(robot_xy, "robot_xy");
  TORCH_CHECK(age.is_cuda() && age.scalar_type() == at::kFloat &&
      age.sizes() == torch::IntArrayRef({n, p}) && age.is_contiguous() &&
      age.device() == points.device(), "age must be contiguous HIP float [N,P]");
  TORCH_CHECK(free.is_cuda() && free.scalar_type() == at::kBool &&
      free.sizes() == torch::IntArrayRef({n, p}) && free.is_contiguous() &&
      free.device() == points.device(), "free must be contiguous HIP bool [N,P]");
  TORCH_CHECK(midfield.is_cuda() && midfield.scalar_type() == at::kBool &&
      midfield.sizes() == torch::IntArrayRef({n, p}) && midfield.is_contiguous() &&
      midfield.device() == points.device(), "midfield must be contiguous HIP bool [N,P]");
  c10::cuda::CUDAGuard guard(points.device());
  auto costs = torch::empty({n, p}, points.options());
  auto nearby = torch::empty({n, p}, points.options().dtype(at::kBool));
  candidate_cost_nearby_launch(points.data_ptr<float>(), intake_xy.data_ptr<float>(),
      robot_xy.data_ptr<float>(), age.data_ptr<float>(), free.data_ptr<bool>(),
      midfield.data_ptr<bool>(), costs.data_ptr<float>(), nearby.data_ptr<bool>(),
      n, p, static_cast<float>(age_weight),
      c10::cuda::getCurrentCUDAStream(points.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return {costs, nearby};
}


std::tuple<torch::Tensor, torch::Tensor, torch::Tensor> candidate_top4_with_nearby(
    torch::Tensor points, torch::Tensor intake_xy, torch::Tensor robot_xy,
    torch::Tensor age, torch::Tensor free, torch::Tensor midfield,
    double age_weight) {
  TORCH_CHECK(points.is_cuda() && points.scalar_type() == at::kFloat &&
      points.dim() == 3 && points.size(2) == 2 && points.is_contiguous(),
      "points must be contiguous HIP float [N,P,2]");
  const auto n = points.size(0), p = points.size(1);
  auto check_xy = [&](const torch::Tensor& xy, const char* name) {
    TORCH_CHECK(xy.is_cuda() && xy.scalar_type() == at::kFloat &&
        xy.sizes() == torch::IntArrayRef({n, 2}) && xy.is_contiguous() &&
        xy.device() == points.device(), name, " must be contiguous HIP float [N,2]");
  };
  check_xy(intake_xy, "intake_xy");
  check_xy(robot_xy, "robot_xy");
  TORCH_CHECK(age.is_cuda() && age.scalar_type() == at::kFloat &&
      age.sizes() == torch::IntArrayRef({n, p}) && age.is_contiguous() &&
      age.device() == points.device(), "age must be contiguous HIP float [N,P]");
  for (const auto& mask : {free, midfield}) {
    TORCH_CHECK(mask.is_cuda() && mask.scalar_type() == at::kBool &&
        mask.sizes() == torch::IntArrayRef({n, p}) && mask.is_contiguous() &&
        mask.device() == points.device(), "masks must be contiguous HIP bool [N,P]");
  }
  TORCH_CHECK(p >= 4, "at least four candidate positions are required");
  c10::cuda::CUDAGuard guard(points.device());
  auto indices = torch::empty({n, 4}, points.options().dtype(at::kLong));
  auto nearest = torch::empty({n, 4}, points.options());
  auto nearby = torch::empty({n}, points.options().dtype(at::kBool));
  candidate_top4_nearby_launch(points.data_ptr<float>(), intake_xy.data_ptr<float>(),
      robot_xy.data_ptr<float>(), age.data_ptr<float>(), free.data_ptr<bool>(),
      midfield.data_ptr<bool>(), indices.data_ptr<int64_t>(), nearest.data_ptr<float>(),
      nearby.data_ptr<bool>(), n, p, static_cast<float>(age_weight),
      c10::cuda::getCurrentCUDAStream(points.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return {indices, nearest, nearby};
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("candidates", &candidates, "Fused fuel-candidate distance and top-four ranking");
  m.def("candidate_top4_with_nearby", &candidate_top4_with_nearby,
      "Fused age-adjusted fuel top-four and nearby-midfield ranking");
  m.def("candidate_costs_with_nearby", &candidate_costs_with_nearby,
      "Fused age-adjusted fuel costs and nearby-midfield mask");
}
