// !!! This is a file automatically generated by hipify!!!
#include <torch/extension.h>
#include <c10/hip/HIPGuard.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime_api.h>
#include <algorithm>
#include <cmath>
#include <utility>
#include <vector>

void pack_launch(const float* base, const float* route, const float* local0,
    const float* local1, const float* possession, const float* match,
    const float* candidate, const float* action_mask, const float* speed,
    const float* omega, float* output, int64_t rows, float inv_length,
    float inv_width, float inv_max_dim, float inv_pi, float inv_16_54,
    float inv_8_07, bool normalize, hipStream_t stream);
void pack_fused_launch(const float* base, const float* route, const float* local1,
    const float* possession, const float* match, const float* action_mask,
    const float* speed, const float* omega, const float* track_pos,
    const float* track_vel, const int64_t* indices, const bool* valid,
    const float* nearest, const float* own_pose, const float* other_pose,
    const float* own_count, const float* robot_length, const float* robot_width,
    const float* hub, float* output, int64_t rows, int64_t piece_count,
    int64_t track_pos_row_stride, int64_t track_vel_row_stride,
    float field_length, float field_width, int fuel_capacity,
    float inv_length, float inv_width, float inv_max_dim, float inv_pi,
    float inv_16_54, float inv_8_07, bool normalize, hipStream_t stream);

torch::Tensor pack(torch::Tensor base, torch::Tensor route, torch::Tensor local0,
    torch::Tensor local1, torch::Tensor possession, torch::Tensor match,
    torch::Tensor candidate, torch::Tensor action_mask, torch::Tensor speed,
    torch::Tensor omega, double field_length, double field_width, bool normalize) {
  const int64_t rows = base.size(0);
  const std::vector<std::pair<int64_t, int64_t>> expected = {
      {rows, 35}, {rows, 3}, {rows, 20}, {rows, 20}, {rows, 2},
      {rows, 9}, {rows, 40}, {rows, 8}, {rows, 2}, {rows, 2}};
  std::vector<torch::Tensor> inputs = {base, route, local0, local1, possession,
      match, candidate, action_mask, speed, omega};
  TORCH_CHECK(base.is_cuda() && base.scalar_type() == at::kFloat,
              "prototype inputs must be float32 device tensors");
  TORCH_CHECK(inputs.size() == expected.size(), "feature input count mismatch");
  for (size_t i = 0; i < inputs.size(); ++i) {
    TORCH_CHECK(inputs[i].is_cuda() && inputs[i].device() == base.device() &&
                inputs[i].scalar_type() == at::kFloat && inputs[i].is_contiguous(),
                "all prototype inputs must be contiguous float32 tensors on one device");
    TORCH_CHECK(inputs[i].dim() == 2 && inputs[i].size(0) == expected[i].first &&
                inputs[i].size(1) == expected[i].second,
                "invalid feature block shape at index ", i);
  }
  c10::cuda::CUDAGuard guard(base.device());
  auto output = torch::empty({rows, 137}, base.options());
  pack_launch(base.data_ptr<float>(), route.data_ptr<float>(), local0.data_ptr<float>(),
      local1.data_ptr<float>(), possession.data_ptr<float>(), match.data_ptr<float>(),
      candidate.data_ptr<float>(), action_mask.data_ptr<float>(), speed.data_ptr<float>(),
      omega.data_ptr<float>(), output.data_ptr<float>(), rows,
      static_cast<float>(1.0 / field_length),
      static_cast<float>(1.0 / field_width),
      static_cast<float>(1.0 / std::max(field_length, field_width)),
      static_cast<float>(1.0 / M_PI), static_cast<float>(1.0 / 16.54),
      static_cast<float>(1.0 / 8.07), normalize,
      c10::cuda::getCurrentCUDAStream(base.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return output;
}

torch::Tensor pack_fused(torch::Tensor base, torch::Tensor route,
    torch::Tensor local1, torch::Tensor possession, torch::Tensor match,
    torch::Tensor action_mask, torch::Tensor speed, torch::Tensor omega,
    torch::Tensor track_pos, torch::Tensor track_vel, torch::Tensor indices,
    torch::Tensor valid, torch::Tensor nearest, torch::Tensor own_pose,
    torch::Tensor other_pose, torch::Tensor own_count, torch::Tensor robot_length,
    torch::Tensor robot_width, torch::Tensor hub, double field_length,
    double field_width, int fuel_capacity, bool normalize) {
  const int64_t rows = base.size(0);
  const int64_t piece_count = track_pos.size(1);
  std::vector<torch::Tensor> inputs = {base, route, local1, possession, match,
      action_mask, speed, omega, track_pos, track_vel, indices, valid, nearest,
      own_pose, other_pose, own_count, robot_length, robot_width, hub};
  TORCH_CHECK(base.is_cuda() && base.scalar_type() == at::kFloat,
              "prototype inputs must be float32 device tensors");
  for (size_t i = 0; i < inputs.size(); ++i) {
    TORCH_CHECK(inputs[i].is_cuda() && inputs[i].device() == base.device(),
                "fused feature inputs must be on one device");
    if (i != 8 && i != 9) {
      TORCH_CHECK(inputs[i].is_contiguous(),
                  "fused feature input must be contiguous at index ", i);
    }
  }
  const int64_t n = rows;
  TORCH_CHECK(base.dim() == 2 && base.size(0) == n && base.size(1) == 35 &&
      route.dim() == 2 && route.size(0) == n && route.size(1) == 3 &&
      local1.dim() == 2 && local1.size(0) == n && local1.size(1) == 20 &&
      possession.dim() == 2 && possession.size(0) == n && possession.size(1) == 2 &&
      match.dim() == 2 && match.size(0) == n && match.size(1) == 9 &&
      action_mask.dim() == 2 && action_mask.size(0) == n && action_mask.size(1) == 8 &&
      speed.dim() == 2 && speed.size(0) == n && speed.size(1) == 2 &&
      omega.dim() == 2 && omega.size(0) == n && omega.size(1) == 2 &&
      track_pos.dim() == 3 && track_pos.size(0) == n && track_pos.size(1) == piece_count &&
      track_pos.size(2) == 2 && track_vel.dim() == 3 && track_vel.size(0) == n &&
      track_vel.size(1) == piece_count && track_vel.size(2) == 2 &&
      track_pos.stride(1) == 2 && track_pos.stride(2) == 1 &&
      track_vel.stride(1) == 2 && track_vel.stride(2) == 1 &&
      indices.dim() == 2 && indices.size(0) == n && indices.size(1) == 4 &&
      valid.dim() == 2 && valid.size(0) == n && valid.size(1) == 4 &&
      nearest.dim() == 2 && nearest.size(0) == n && nearest.size(1) == 4 &&
      own_pose.dim() == 2 && own_pose.size(0) == n && own_pose.size(1) == 3 &&
      other_pose.dim() == 2 && other_pose.size(0) == n && other_pose.size(1) == 2 &&
      own_count.dim() == 1 && own_count.size(0) == n &&
      robot_length.dim() == 1 && robot_length.size(0) == n &&
      robot_width.dim() == 1 && robot_width.size(0) == n &&
      hub.dim() == 1 && hub.size(0) == 2, "invalid fused feature input shape");
  TORCH_CHECK(indices.scalar_type() == at::kLong && valid.scalar_type() == at::kBool,
              "candidate indices/validity must be int64/bool");
  for (size_t i : {size_t(0),size_t(1),size_t(2),size_t(3),size_t(4),size_t(5),
       size_t(6),size_t(7),size_t(8),size_t(9),size_t(12),size_t(13),size_t(14),
       size_t(15),size_t(16),size_t(17),size_t(18)}) {
    TORCH_CHECK(inputs[i].scalar_type() == at::kFloat,
                "fused feature float input dtype mismatch at index ", i);
  }
  TORCH_CHECK(nearest.scalar_type() == at::kFloat, "nearest must be float32");
  c10::cuda::CUDAGuard guard(base.device());
  auto output = torch::empty({rows, 137}, base.options());
  const float inv_length = static_cast<float>(1.0 / field_length);
  const float inv_width = static_cast<float>(1.0 / field_width);
  const float inv_max_dim = static_cast<float>(1.0 / std::max(field_length, field_width));
  const float inv_pi = static_cast<float>(1.0 / M_PI);
  const float inv_16_54 = static_cast<float>(1.0 / 16.54);
  const float inv_8_07 = static_cast<float>(1.0 / 8.07);
  pack_fused_launch(base.data_ptr<float>(), route.data_ptr<float>(), local1.data_ptr<float>(),
      possession.data_ptr<float>(), match.data_ptr<float>(), action_mask.data_ptr<float>(),
      speed.data_ptr<float>(), omega.data_ptr<float>(), track_pos.data_ptr<float>(),
      track_vel.data_ptr<float>(), indices.data_ptr<int64_t>(), valid.data_ptr<bool>(),
      nearest.data_ptr<float>(), own_pose.data_ptr<float>(), other_pose.data_ptr<float>(),
      own_count.data_ptr<float>(), robot_length.data_ptr<float>(), robot_width.data_ptr<float>(),
      hub.data_ptr<float>(), output.data_ptr<float>(), rows, piece_count,
      track_pos.stride(0), track_vel.stride(0),
      static_cast<float>(field_length), static_cast<float>(field_width), fuel_capacity,
      inv_length, inv_width, inv_max_dim, inv_pi, inv_16_54, inv_8_07, normalize,
      c10::cuda::getCurrentCUDAStream(base.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return output;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("pack", &pack,
        "Pack strategic raw observation feature blocks (HIP prototype)");
  m.def("pack_fused", &pack_fused,
        "Fuse local/candidate strategic features with raw observation packing (HIP proto)");
}
