// !!! This is a file automatically generated by hipify!!!
// Isolated prototype: exact AD* blocked-grid construction for parity/timing.
#include <torch/extension.h>
#include <c10/hip/HIPGuard.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime_api.h>

void blocked_grid_launch(const float*, const float*, const float*, const float*,
    const float*, const float*, const float*, const float*, const float*,
    int, int, int, int, int, int, float, float,
    float, bool, bool, bool*, hipStream_t);

torch::Tensor blocked_grid(torch::Tensor heading, torch::Tensor length,
    torch::Tensor width, torch::Tensor x, torch::Tensor y, torch::Tensor boxes,
    torch::Tensor bumps, torch::Tensor circles, torch::Tensor dynamic,
    double field_length, double field_width, double grid_clearance,
    bool avoid_bumps) {
  TORCH_CHECK(heading.is_cuda() && heading.scalar_type() == at::kFloat && heading.dim() == 1,
              "heading must be accelerator float32 [N]");
  const auto n = heading.size(0), nx = x.numel(), ny = y.numel();
  TORCH_CHECK(length.sizes() == heading.sizes() && width.sizes() == heading.sizes() &&
              x.dim() == 1 && y.dim() == 1 && boxes.dim() == 2 && boxes.size(1) == 4 &&
              bumps.dim() == 2 && bumps.size(1) == 4 &&
              circles.dim() == 2 && circles.size(1) == 3 &&
              (dynamic.numel() == 0 || (dynamic.dim() == 2 && dynamic.size(0) == n &&
                                        dynamic.size(1) == 4)),
              "blocked-grid input shape mismatch");
  for (const auto& t : {heading, length, width, x, y, boxes, bumps, circles})
    TORCH_CHECK(t.is_cuda() && t.scalar_type() == at::kFloat &&
                t.device() == heading.device() && t.is_contiguous(),
                "blocked-grid float inputs must be contiguous on one accelerator");
  TORCH_CHECK(dynamic.is_cuda() && dynamic.scalar_type() == at::kFloat &&
              dynamic.device() == heading.device() && dynamic.is_contiguous(),
              "dynamic defender must be contiguous accelerator float32");
  c10::cuda::CUDAGuard guard(heading.device());
  auto out = torch::empty({n, nx, ny}, heading.options().dtype(torch::kBool));
  blocked_grid_launch(heading.data_ptr<float>(), length.data_ptr<float>(),
      width.data_ptr<float>(), x.data_ptr<float>(), y.data_ptr<float>(),
      boxes.data_ptr<float>(), bumps.data_ptr<float>(), circles.data_ptr<float>(),
      dynamic.numel() ? dynamic.data_ptr<float>() : nullptr,
      static_cast<int>(n), static_cast<int>(nx), static_cast<int>(ny),
      static_cast<int>(boxes.size(0)), static_cast<int>(bumps.size(0)),
      static_cast<int>(circles.size(0)), static_cast<float>(field_length),
      static_cast<float>(field_width), static_cast<float>(grid_clearance),
      avoid_bumps, dynamic.numel() != 0, out.data_ptr<bool>(),
      c10::cuda::getCurrentCUDAStream(heading.get_device()));
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return out;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("blocked_grid", &blocked_grid,
        "Isolated fused AD* blocked-grid prototype (HIP)");
}
