// !!! This is a file automatically generated by hipify!!!
#include <torch/extension.h>
#include <c10/hip/HIPStream.h>
#include <hip/hip_runtime.h>

void contact_3v3_launch(float*, float*, const float*, const float*,
    const float*, const float*, const float*, const float*, const bool*,
    bool*, bool*, bool*, bool*, const float*, int, const float*, int, int,
    float, float, int, hipStream_t);

void contact_3v3(torch::Tensor pose, torch::Tensor velocity,
    torch::Tensor length, torch::Tensor width, torch::Tensor mass,
    torch::Tensor yaw_inertia_multiplier, torch::Tensor mu,
    torch::Tensor wall_mu, torch::Tensor active, torch::Tensor robot_contact,
    torch::Tensor opponent_contact, torch::Tensor field_contact,
    torch::Tensor wall_contact, torch::Tensor obstacles,
    torch::Tensor field_colliders, int64_t iterations, double field_length,
    double field_width) {
  const auto n = pose.size(0);
  TORCH_CHECK(pose.is_cuda() && pose.scalar_type() == at::kFloat &&
              pose.sizes() == torch::IntArrayRef({n, 6, 3}),
              "pose must be CUDA float [world,6,3]");
  TORCH_CHECK(velocity.sizes() == pose.sizes() && velocity.scalar_type() == at::kFloat,
              "velocity must match pose");
  TORCH_CHECK(length.sizes() == torch::IntArrayRef({n, 6}) &&
              width.sizes() == length.sizes() && mass.sizes() == length.sizes() &&
              yaw_inertia_multiplier.sizes() == length.sizes() &&
              mu.sizes() == torch::IntArrayRef({n}) && wall_mu.sizes() == mu.sizes(),
              "robot property shape mismatch");
  TORCH_CHECK(active.sizes() == mu.sizes() && active.scalar_type() == at::kBool &&
              robot_contact.sizes() == mu.sizes() && robot_contact.scalar_type() == at::kBool &&
              opponent_contact.sizes() == mu.sizes() && opponent_contact.scalar_type() == at::kBool &&
              field_contact.sizes() == torch::IntArrayRef({n, 6}) && field_contact.scalar_type() == at::kBool &&
              wall_contact.sizes() == torch::IntArrayRef({n, 6, 2}) && wall_contact.scalar_type() == at::kBool,
              "contact mask shape or dtype mismatch");
  TORCH_CHECK(obstacles.dim() == 2 && obstacles.size(1) == 3 && obstacles.scalar_type() == at::kFloat &&
              field_colliders.dim() == 2 && field_colliders.size(1) == 4 &&
              field_colliders.scalar_type() == at::kFloat, "collider shape mismatch");
  TORCH_CHECK(iterations >= 1, "iterations must be positive");
  for (const auto& t : {pose, velocity, length, width, mass, yaw_inertia_multiplier,
                        mu, wall_mu, active, robot_contact, opponent_contact,
                        field_contact, wall_contact, obstacles, field_colliders})
    TORCH_CHECK(t.is_cuda() && t.is_contiguous() && t.device() == pose.device(),
                "contact tensors must be contiguous on the same accelerator");
  contact_3v3_launch(pose.data_ptr<float>(), velocity.data_ptr<float>(),
      length.data_ptr<float>(), width.data_ptr<float>(), mass.data_ptr<float>(),
      yaw_inertia_multiplier.data_ptr<float>(), mu.data_ptr<float>(), wall_mu.data_ptr<float>(),
      active.data_ptr<bool>(), robot_contact.data_ptr<bool>(), opponent_contact.data_ptr<bool>(),
      field_contact.data_ptr<bool>(), wall_contact.data_ptr<bool>(), obstacles.data_ptr<float>(),
      static_cast<int>(obstacles.size(0)), field_colliders.data_ptr<float>(),
      static_cast<int>(field_colliders.size(0)), static_cast<int>(n),
      static_cast<float>(field_length), static_cast<float>(field_width),
      static_cast<int>(iterations), c10::cuda::getCurrentCUDAStream(pose.get_device()));
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("contact_pipeline", &contact_3v3, "Fused six-robot contact pipeline (HIP)");
}
